In [4]:
import os
import numpy as np
target = []
obs_seq = []
hidden_var_name = ('sunny',  'foggy', 'rainy')
observation_var_name = ('no', 'yes')
hidden_var = {
    hidden_var_name[0]: 0,
    hidden_var_name[1]: 1,
    hidden_var_name[2]: 2,
    }

observation_var = {
    observation_var_name[0]: 0,
    observation_var_name[1]: 1,
    }
with open('input.txt') as f:
    for line in f:
        hidden, observe = line.strip().split(',')
        target.append(hidden_var[hidden])
        obs_seq.append(observation_var[observe])
#     print(target)
X = np.array([obs_seq])
x_ = [obs_seq[i:i+6] for i in range(0,len(obs_seq),6)]
y = [target[i:i+6] for i in range(0, len(target),6)]
x_ = np.array(x_)
y = np.array(y)
print(x_)

[[1 0 0 1 1 1]
 [1 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 1 1 0 1 0]
 [0 0 0 0 1 0]
 [1 1 0 0 1 0]
 [0 1 0 0 1 0]
 [1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [0 1 1 0 0 1]
 [0 1 1 1 0 1]
 [0 1 0 1 1 1]
 [1 1 0 0 0 1]
 [1 1 0 1 1 1]
 [1 1 0 0 0 0]
 [1 0 1 1 0 0]
 [1 0 1 0 0 0]
 [1 0 1 1 1 0]
 [0 0 0 1 1 1]
 [1 1 0 1 1 0]
 [1 1 0 0 1 0]
 [0 0 0 1 1 1]
 [1 0 0 1 1 1]
 [1 1 0 0 0 0]
 [1 1 1 1 1 0]
 [1 1 0 1 1 1]
 [0 1 1 1 0 1]
 [0 0 1 1 1 1]
 [1 1 1 0 0 0]
 [0 0 0 1 0 0]
 [0 1 0 1 1 0]
 [1 0 0 1 1 1]
 [0 0 1 1 1 1]
 [0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 0 1 0]
 [1 0 1 0 1 1]
 [1 0 1 0 1 1]
 [0 1 0 1 1 0]
 [0 0 0 0 0 0]
 [1 1 1 0 0 0]
 [0 1 0 0 1 1]
 [1 1 0 1 1 1]
 [1 1 1 0 1 0]
 [0 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 1 0 1 1 0]
 [1 0 1 1 1 1]
 [0 0 1 0 0 0]
 [1 0 1 0 0 0]]


In [132]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
from hmmlearn import hmm

states = ["Sunny","Foggy", "Rainy"]##隐藏状态
n_states = len(states)##隐藏状态长度

observations = ["no", "yes"]##可观察的状态
n_observations = len(observations)##可观察序列的长度

start_probability = np.array([1/3, 1/3, 1/3])##开始转移概率，即开始是Rainy和Sunny的概率
##隐藏间天气转移混淆矩阵，即Rainy和Sunny之间的转换关系，例如[0,0]表示今天Rainy，明天Rainy的概率
transition_probability = np.array([
  [0.2, 0.79, 0.01],
  [0.2, 0.7, 0.1],
  [0.01, 0.25, 0.74]
])
##隐藏状态天气和可视行为混淆矩阵，例如[0,0]表示今天Rainy，walk行为的概率为0.1
emission_probability = np.array([
  [0.8,0.2],
  [0.4,0.6],
  [0.2,0.8]
])

#构建了一个MultinomialHMM模型，这模型包括开始的转移概率，隐藏间天气转换混淆矩阵（transmat），隐藏状态天气和可视行为混淆矩阵emissionprob，对模型参数初始化
model = hmm.MultinomialHMM(n_components=n_states,verbose=1)
model.startprob_= start_probability
model.transmat_ = transition_probability
model.emissionprob_ = emission_probability

bob_Actions = np.array([[1, 0, 1, 1, 1, 0]]).T
bob_Actions_for_obs = np.array([1, 0, 1, 1, 1, 0])
print(bob_Actions_for_obs)
#############################################Viterbi###########################################
# logprob, weathers = model.decode(bob_Actions, algorithm="viterbi")
# print(weathers)
# print ("Bob Actions:", ", ".join(map(lambda x: observations[x], bob_Actions_for_obs)))
# print ("weathers:", ", ".join(map(lambda x: states[x], weathers)))
# print (logprob)#该参数反映模型拟合的好坏,数值越大越好
# score = model.score(bob_Actions, lengths=None)
# print (score)
# # 结果为-6.892170869，其实真正的概率是以自然数e为底数ln(P) = -6.892170869,所以概率P = 0.00101570648021
# import math
# print (math.exp(-6.892170869))
# # 解决問题3，學習問题，僅给X，估計模型参數,基於EM算法的求解
# # 通過model.fit(X, lengths=None)来進行訓練後自己生成一个模型
# # 不需要model.startprob_,model.transmat_,model.emissionprob_

####################################################Traing Problem#######################################################
print("==============================")
import numpy as np
from hmmlearn import hmm
 
states = ["Sunny", "Foggy", "Rainy"]##隐藏状态
n_states = len(states)##隐藏状态长度
 
observations = ["no", "yes"]##可观察的状态
n_observations = len(observations)##可观察序列的长度
model = hmm.MultinomialHMM(n_components=n_states, n_iter=1000, tol=0.01)
score_list = []
i = 0
acc = 0
w = np.array([[1,0,1,0,0,0]]).T
while(acc <0.8):
    model.fit(x_)
    print("Score=" + str(math.exp(model.score(x_))))
    print("================predict===============")
    out = model.predict(w, lengths=None)
    print(out)
    print(model.predict_proba(w))
    count = 0
    for _ in range(len(out)):
        if out[_] == y[0][_]:
            count += 1
    acc = count/len(out)
    print("acc = %.2f " %(acc*100))
    if acc > 0.8:
        output = open('model.pkl', 'wb')
        s = pickle.dump(model, output)
        output.close()
# print (model.startprob_)
# print (model.transmat_)
# print (model.emissionprob_)
# #print (model.score(X))
# print(math.exp(model.score(X)))
# print("============Predict==================")
# print (model.predict(bob_Actions, lengths=None))

# print model.predict_proba(bob_Actions, lengths=None)# 预测各个隐藏状态的概率

# # 在生成的模型中，可以随机生成随机生成一个模型的Z和X
# X,Z = model.sample(n_samples=5, random_state=None)
# print "Bob Actions:", ", ".join(map(lambda x: observations[x], X))
# print "weathers:", ", ".join(map(lambda x: states[x], Z))

[1 0 1 1 1 0]
Score=1.2849215435997747e-90
================predict===============
[2 1 2 1 1 1]
[[2.89111588e-01 9.55293025e-13 7.10888412e-01]
 [2.39281324e-01 5.71035178e-01 1.89683497e-01]
 [4.57825957e-01 4.52400852e-02 4.96933957e-01]
 [2.03200814e-01 6.37294571e-01 1.59504615e-01]
 [1.76961978e-01 6.86961641e-01 1.36076381e-01]
 [1.89883195e-01 6.63800792e-01 1.46316013e-01]]
acc = 33.33 
Score=7.816886522284122e-91
================predict===============
[1 0 1 0 0 0]
[[0.0075979  0.49953865 0.49286345]
 [0.41714469 0.29112915 0.29172616]
 [0.21394872 0.39343207 0.39261921]
 [0.42321195 0.28808589 0.28870217]
 [0.42622755 0.28657253 0.28719992]
 [0.42466405 0.28735627 0.28797968]]
acc = 66.67 
Score=8.894144949145426e-91
================predict===============
[1 2 1 2 2 2]
[[3.89148103e-02 9.60752493e-01 3.32696226e-04]
 [3.41693628e-01 2.58087584e-01 4.00218788e-01]
 [3.26628017e-01 4.72053101e-01 2.01318882e-01]
 [3.38201031e-01 2.46621003e-01 4.15177966e-01]
 [3.37061117e-01 2

[0 1 0 1 1 1]
[[0.51665614 0.0106049  0.47273896]
 [0.29072461 0.41455653 0.29471887]
 [0.39096594 0.22327976 0.3857543 ]
 [0.28810572 0.41967449 0.2922198 ]
 [0.28685883 0.4221031  0.29103807]
 [0.28750147 0.42084177 0.29165676]]
acc = 16.67 
Score=1.4393781306079946e-90
================predict===============
[0 1 0 1 1 1]
[[9.99981277e-01 3.77543275e-07 1.83453142e-05]
 [9.96455883e-02 4.69064577e-01 4.31289835e-01]
 [5.24048019e-01 2.08016787e-01 2.67935194e-01]
 [7.04749767e-02 5.01899619e-01 4.27625405e-01]
 [5.85519526e-02 5.15704606e-01 4.25743441e-01]
 [6.47289826e-02 5.07258523e-01 4.28012495e-01]]
acc = 16.67 
Score=1.4500527065898113e-90
================predict===============
[1 0 1 0 0 0]
[[4.33571428e-09 8.76511276e-01 1.23488720e-01]
 [7.11362747e-01 8.82375831e-02 2.00399670e-01]
 [1.56390774e-01 4.38217719e-01 4.05391507e-01]
 [7.68115118e-01 6.96240369e-02 1.62260845e-01]
 [8.02728447e-01 5.72138241e-02 1.40057729e-01]
 [7.84832325e-01 6.25788731e-02 1.52588802e-01]]
a

Score=1.4598457776060727e-90
================predict===============
[2 0 2 0 0 0]
[[2.79620394e-12 7.66163125e-03 9.92338369e-01]
 [5.24320244e-01 3.53986288e-01 1.21693468e-01]
 [5.11673321e-02 3.65424674e-01 5.83407993e-01]
 [5.91532623e-01 3.12490089e-01 9.59772878e-02]
 [6.32692478e-01 2.87699855e-01 7.96076676e-02]
 [6.10154127e-01 3.03008685e-01 8.68371882e-02]]
acc = 66.67 
Score=1.6324920340911493e-90
================predict===============
[0 2 0 2 2 2]
[[9.99675120e-01 3.23960782e-04 9.18768914e-07]
 [9.67135525e-03 4.50301787e-01 5.40026858e-01]
 [5.82401158e-01 2.70730794e-01 1.46868048e-01]
 [6.98868293e-03 4.27581390e-01 5.65429927e-01]
 [5.66856680e-03 4.15913550e-01 5.78417883e-01]
 [6.34825736e-03 4.23803720e-01 5.69848023e-01]]
acc = 0.00 
Score=9.17552287693659e-91
================predict===============
[1 0 1 0 0 0]
[[3.06312330e-04 9.64900404e-01 3.47932832e-02]
 [4.52832066e-01 2.12462540e-01 3.34705394e-01]
 [2.44200674e-01 4.20759072e-01 3.35040254e-01]
 [4.69857

Score=1.2906126513764244e-90
================predict===============
[2 0 2 1 1 1]
[[2.60850518e-06 2.78688050e-11 9.99997391e-01]
 [3.86467564e-01 4.33482614e-01 1.80049821e-01]
 [3.06555808e-01 2.09288708e-01 4.84155484e-01]
 [3.66029070e-01 5.06175373e-01 1.27795556e-01]
 [3.57910544e-01 5.34248066e-01 1.07841391e-01]
 [3.65530567e-01 5.17055983e-01 1.17413450e-01]]
acc = 50.00 
Score=1.4808948752297627e-90
================predict===============
[2 1 2 1 1 1]
[[1.23544489e-02 1.15617802e-21 9.87645551e-01]
 [3.46770176e-01 5.41704128e-01 1.11525697e-01]
 [3.78531720e-01 4.60267102e-03 6.16865609e-01]
 [3.05414855e-01 6.04602449e-01 8.99826958e-02]
 [2.78727439e-01 6.46711798e-01 7.45607629e-02]
 [2.94878741e-01 6.23858531e-01 8.12627282e-02]]
acc = 33.33 
Score=1.3922669796967203e-90
================predict===============
[1 0 1 0 0 0]
[[7.66687976e-11 9.99490946e-01 5.09054135e-04]
 [4.56719009e-01 1.62746577e-01 3.80534414e-01]
 [1.11008709e-01 5.68110665e-01 3.20880626e-01]
 [5.28

================predict===============
[0 1 0 1 1 1]
[[9.81622949e-01 3.45489378e-14 1.83770512e-02]
 [2.01215971e-01 4.87950541e-01 3.10833488e-01]
 [4.82977536e-01 1.26318539e-01 3.90703925e-01]
 [1.62166853e-01 5.82083412e-01 2.55749735e-01]
 [1.35992321e-01 6.37543081e-01 2.26464599e-01]
 [1.45781127e-01 6.10196990e-01 2.44021883e-01]]
acc = 16.67 
Score=8.168020367793776e-91
================predict===============
[0 2 0 2 2 2]
[[0.742805   0.25398477 0.00321023]
 [0.26212937 0.30852232 0.42934831]
 [0.41975195 0.36566912 0.21457893]
 [0.25667314 0.30483724 0.43848962]
 [0.25405371 0.30320041 0.44274588]
 [0.25533501 0.30416521 0.44049979]]
acc = 0.00 
Score=9.019720980498555e-91
================predict===============
[0 1 0 1 1 1]
[[9.76116834e-01 8.66308327e-04 2.30168575e-02]
 [2.34319635e-01 4.13431410e-01 3.52248955e-01]
 [4.50314533e-01 2.34781224e-01 3.14904243e-01]
 [2.23389770e-01 4.25850440e-01 3.50759790e-01]
 [2.19568839e-01 4.29999465e-01 3.50431696e-01]
 [2.21467004e-

Score=1.5837065655148284e-90
================predict===============
[1 2 1 2 2 2]
[[6.19639359e-05 9.99937281e-01 7.55502798e-07]
 [4.56354727e-01 5.13048897e-02 4.92340383e-01]
 [2.11471003e-01 6.59743041e-01 1.28785957e-01]
 [4.48129155e-01 3.82760758e-02 5.13594769e-01]
 [4.43384950e-01 3.13153996e-02 5.25299650e-01]
 [4.46952403e-01 3.48843253e-02 5.18163272e-01]]
acc = 16.67 
Score=9.3572622460417e-91
================predict===============
[0 1 0 1 1 1]
[[0.99155084 0.00181658 0.00663258]
 [0.18633662 0.42843848 0.38522491]
 [0.39938924 0.2903558  0.31025496]
 [0.17565548 0.43711438 0.38723014]
 [0.17269719 0.43943412 0.38786869]
 [0.17422265 0.43805128 0.38772607]]
acc = 16.67 
Score=1.5860015071487425e-90
================predict===============
[0 2 0 2 2 2]
[[9.99328682e-01 6.71317548e-04 1.54871509e-10]
 [5.72284079e-02 4.30104650e-01 5.12666942e-01]
 [7.15707503e-01 2.49201341e-01 3.50911565e-02]
 [4.46656438e-02 4.05924354e-01 5.49410002e-01]
 [3.67635692e-02 3.90619399e-01 5

Score=1.3131036973294658e-90
================predict===============
[2 0 2 1 1 1]
[[4.21554204e-05 5.74942510e-17 9.99957845e-01]
 [3.49916148e-01 4.51845918e-01 1.98237934e-01]
 [3.40355717e-01 2.09522238e-01 4.50122045e-01]
 [2.83849716e-01 5.66395744e-01 1.49754540e-01]
 [2.57736213e-01 6.17262045e-01 1.25001742e-01]
 [2.76971618e-01 5.89097339e-01 1.33931043e-01]]
acc = 50.00 
Score=8.651985098843063e-91
================predict===============
[2 1 2 1 1 1]
[[0.00992006 0.00961398 0.98046596]
 [0.37537588 0.37596812 0.248656  ]
 [0.27970355 0.27888105 0.4414154 ]
 [0.3790679  0.37976248 0.24116963]
 [0.38005556 0.3807752  0.23916924]
 [0.37954316 0.38024478 0.24021206]]
acc = 33.33 
Score=1.1153241711104678e-90
================predict===============
[1 2 1 2 2 2]
[[1.89659552e-03 9.98102754e-01 6.50165827e-07]
 [3.43984522e-01 1.52814334e-01 5.03201144e-01]
 [3.34415440e-01 4.12011649e-01 2.53572911e-01]
 [3.24780426e-01 1.27318007e-01 5.47901566e-01]
 [3.18135014e-01 1.17240525e-01

Score=6.854925560592953e-91
================predict===============
[2 1 2 1 1 1]
[[0.35233735 0.25189109 0.39577156]
 [0.32562732 0.36181645 0.31255622]
 [0.33845462 0.31441104 0.34713433]
 [0.32561705 0.36185117 0.31253178]
 [0.32561267 0.36186602 0.31252131]
 [0.32561498 0.36185824 0.31252678]]
acc = 33.33 
Score=1.3251323449343695e-90
================predict===============
[1 2 1 2 2 2]
[[5.84622053e-04 9.99415378e-01 4.20539992e-17]
 [3.29064267e-01 1.99041183e-01 4.71894550e-01]
 [3.49962627e-01 4.41928427e-01 2.08108946e-01]
 [2.58354940e-01 1.55387304e-01 5.86257756e-01]
 [2.28929291e-01 1.29538578e-01 6.41532131e-01]
 [2.49162239e-01 1.38191030e-01 6.12646731e-01]]
acc = 16.67 
Score=8.784589132770034e-91
================predict===============
[1 2 1 2 2 2]
[[2.26797898e-01 7.72730294e-01 4.71808051e-04]
 [2.91224753e-01 2.33610797e-01 4.75164450e-01]
 [3.72693237e-01 4.19016317e-01 2.08290446e-01]
 [2.82947475e-01 2.23695439e-01 4.93357086e-01]
 [2.78853062e-01 2.18388123e-01 

[1 2 1 2 2 2]
[[2.33057980e-01 7.66942020e-01 1.40886721e-10]
 [2.16370055e-01 1.45154428e-01 6.38475517e-01]
 [4.39525942e-01 4.77687760e-01 8.27862981e-02]
 [1.80538657e-01 1.19380836e-01 7.00080507e-01]
 [1.56299820e-01 1.00373820e-01 7.43326360e-01]
 [1.68790831e-01 1.08719433e-01 7.22489736e-01]]
acc = 16.67 
Score=1.2385887775404185e-90
================predict===============
[1 2 1 2 2 2]
[[2.87681040e-01 7.12318960e-01 2.95157564e-11]
 [2.37708182e-01 2.06264906e-01 5.56026911e-01]
 [4.05887562e-01 4.24308352e-01 1.69804086e-01]
 [1.92381093e-01 1.66973341e-01 6.40645565e-01]
 [1.66545511e-01 1.42532185e-01 6.90922304e-01]
 [1.79541657e-01 1.53028536e-01 6.67429807e-01]]
acc = 16.67 
Score=1.4591240618043669e-90
================predict===============
[2 1 2 1 1 1]
[[1.63690907e-03 3.31234263e-09 9.98363088e-01]
 [3.32983672e-01 5.83890264e-01 8.31260641e-02]
 [3.56723414e-01 2.09627482e-01 4.33649104e-01]
 [2.84869825e-01 6.55241178e-01 5.98889971e-02]
 [2.63973708e-01 6.8687464

Score=7.201269921130714e-91
================predict===============
[0 1 0 1 1 1]
[[0.50684986 0.09906234 0.3940878 ]
 [0.28690566 0.40626271 0.30683163]
 [0.36216798 0.28799988 0.34983214]
 [0.28634727 0.40719956 0.30645316]
 [0.28613352 0.40755595 0.30631053]
 [0.28624357 0.40736928 0.30638715]]
acc = 16.67 
Score=6.866359502081255e-91
================predict===============
[0 2 0 2 2 2]
[[0.39833417 0.35178864 0.24987719]
 [0.30495769 0.32300246 0.37203985]
 [0.3437059  0.33711519 0.31917891]
 [0.30492399 0.3229883  0.37208771]
 [0.30490951 0.32298226 0.37210823]
 [0.30491706 0.32298545 0.37209748]]
acc = 0.00 
Score=7.944436942582887e-91
================predict===============
[1 2 1 2 2 2]
[[0.03873074 0.93434357 0.02692569]
 [0.35884382 0.27519869 0.36595749]
 [0.3001033  0.40964929 0.29024741]
 [0.36001897 0.27224577 0.36773526]
 [0.360269   0.27163119 0.36809981]
 [0.36015284 0.27195128 0.36789588]]
acc = 16.67 
Score=1.0760766652159512e-90
================predict===============


Score=1.2100120031528714e-90
================predict===============
[2 1 2 1 1 1]
[[1.67413897e-01 5.60664821e-16 8.32586103e-01]
 [2.96462580e-01 4.46991797e-01 2.56545623e-01]
 [4.04731602e-01 1.53251177e-01 4.42017222e-01]
 [2.37361024e-01 5.54116323e-01 2.08522653e-01]
 [2.05814493e-01 6.16174180e-01 1.78011327e-01]
 [2.21821783e-01 5.88679087e-01 1.89499131e-01]]
acc = 33.33 
Score=1.3633843881111655e-90
================predict===============
[1 0 1 0 0 0]
[[2.39762029e-10 9.99821476e-01 1.78524206e-04]
 [4.77159302e-01 1.48322384e-01 3.74518314e-01]
 [1.76211630e-01 4.93303099e-01 3.30485271e-01]
 [5.52795581e-01 1.08476238e-01 3.38728182e-01]
 [5.86447436e-01 9.07058563e-02 3.22846708e-01]
 [5.66475101e-01 9.89097615e-02 3.34615137e-01]]
acc = 66.67 
Score=1.3494978479582656e-90
================predict===============
[1 2 1 0 0 0]
[[2.06332287e-09 9.99998439e-01 1.55874690e-06]
 [4.20692425e-01 1.77728902e-01 4.01578673e-01]
 [1.87826873e-01 5.49297448e-01 2.62875679e-01]
 [4.72

Score=8.548662119788592e-91
================predict===============
[0 2 0 2 2 2]
[[0.56123552 0.43726254 0.00150194]
 [0.25021799 0.26479321 0.48498881]
 [0.4052419  0.39354067 0.20121744]
 [0.24269102 0.25758851 0.49972047]
 [0.23831196 0.25346173 0.50822631]
 [0.24052227 0.25561566 0.50386207]]
acc = 0.00 
Score=9.78221033903641e-91
================predict===============
[0 1 0 1 1 1]
[[9.92972464e-01 6.51963352e-04 6.37557293e-03]
 [1.85521203e-01 4.37233560e-01 3.77245236e-01]
 [4.33437184e-01 2.60667100e-01 3.05895716e-01]
 [1.70883237e-01 4.51579753e-01 3.77537010e-01]
 [1.66064939e-01 4.56135387e-01 3.77799674e-01]
 [1.68524412e-01 4.53436126e-01 3.78039462e-01]]
acc = 16.67 
Score=1.2952902306126307e-90
================predict===============
[2 0 2 0 0 0]
[[7.57318361e-15 2.94275334e-02 9.70572467e-01]
 [4.64726327e-01 3.16536077e-01 2.18737596e-01]
 [9.45899252e-02 4.01407190e-01 5.04002885e-01]
 [5.56348373e-01 2.64461167e-01 1.79190459e-01]
 [6.13837854e-01 2.34790021e-01 1.

Score=6.890636979637682e-91
================predict===============
[0 1 0 1 1 1]
[[0.42193919 0.2210489  0.35701191]
 [0.31141519 0.36292516 0.32565965]
 [0.35763373 0.3005222  0.34184406]
 [0.31135864 0.36300527 0.32563609]
 [0.31133399 0.36304011 0.3256259 ]
 [0.31134684 0.36302186 0.32563131]]
acc = 16.67 
Score=7.19354630211834e-91
================predict===============
[0 2 0 2 2 2]
[[0.48584958 0.41856898 0.09558144]
 [0.2938418  0.3047939  0.4013643 ]
 [0.36277542 0.35464196 0.28258262]
 [0.29332406 0.30438117 0.40229477]
 [0.29312268 0.30422209 0.40265523]
 [0.29322685 0.30430641 0.40246674]]
acc = 0.00 
Score=8.362657432050635e-91
================predict===============
[0 2 0 2 2 2]
[[0.96086741 0.03025622 0.00887637]
 [0.22806616 0.36436575 0.40756809]
 [0.37899707 0.31934021 0.30166272]
 [0.22366808 0.36500634 0.41132557]
 [0.22268286 0.36518589 0.41213125]
 [0.22318379 0.36518209 0.41163412]]
acc = 0.00 
Score=8.370272061094528e-91
================predict===============
[1 

Score=9.518692574382612e-91
================predict===============
[1 2 1 2 2 2]
[[1.59303943e-02 9.84063909e-01 5.69662537e-06]
 [3.45664369e-01 2.69128736e-01 3.85206894e-01]
 [3.25619139e-01 5.16414286e-01 1.57966575e-01]
 [3.37758640e-01 2.48810080e-01 4.13431280e-01]
 [3.34583092e-01 2.39026574e-01 4.26390334e-01]
 [3.37158246e-01 2.43651655e-01 4.19190099e-01]]
acc = 16.67 
Score=1.2935481953329932e-90
================predict===============
[2 1 2 0 0 0]
[[4.43336288e-11 1.96166954e-06 9.99998038e-01]
 [4.37864897e-01 3.88677448e-01 1.73457655e-01]
 [2.16708408e-01 3.06200526e-01 4.77091066e-01]
 [5.08109378e-01 3.69756390e-01 1.22134232e-01]
 [5.34647936e-01 3.62376329e-01 1.02975735e-01]
 [5.18232505e-01 3.69514721e-01 1.12252774e-01]]
acc = 50.00 
Score=1.3593415841531248e-90
================predict===============
[0 2 0 2 2 2]
[[9.99998023e-01 1.92328554e-06 5.40579757e-08]
 [1.28188323e-01 4.21611675e-01 4.50200002e-01]
 [4.84967331e-01 2.78170847e-01 2.36861822e-01]
 [8.877

Score=1.358081857681818e-90
================predict===============
[1 0 1 2 2 2]
[[2.70117835e-07 9.99999715e-01 1.49573708e-08]
 [3.92256409e-01 2.14440273e-01 3.93303318e-01]
 [1.96733227e-01 6.40442706e-01 1.62824066e-01]
 [4.10965299e-01 1.58813126e-01 4.30221576e-01]
 [4.19399390e-01 1.32814432e-01 4.47786178e-01]
 [4.15818579e-01 1.45870301e-01 4.38311120e-01]]
acc = 33.33 
Score=1.2873760580836578e-90
================predict===============
[1 0 1 0 0 0]
[[2.43882229e-17 9.97801571e-01 2.19842931e-03]
 [4.23925651e-01 2.33790962e-01 3.42283387e-01]
 [1.56740177e-01 4.76054713e-01 3.67205109e-01]
 [5.35707100e-01 1.87487326e-01 2.76805574e-01]
 [5.95205142e-01 1.58239766e-01 2.46555092e-01]
 [5.65970728e-01 1.68112795e-01 2.65916478e-01]]
acc = 66.67 
Score=1.1981508924675614e-90
================predict===============
[1 2 1 2 2 2]
[[6.66298230e-04 9.99317591e-01 1.61106310e-05]
 [3.91960707e-01 1.01361796e-01 5.06677497e-01]
 [3.22341059e-01 3.95803564e-01 2.81855377e-01]
 [3.829

Score=1.2632759704459039e-90
================predict===============
[0 2 0 2 2 2]
[[9.99997579e-01 2.42093305e-06 1.84837851e-10]
 [1.65474585e-01 3.88135029e-01 4.46390386e-01]
 [4.58063554e-01 3.09140468e-01 2.32795977e-01]
 [1.17874950e-01 3.71326245e-01 5.10798804e-01]
 [1.00754980e-01 3.65219750e-01 5.34025270e-01]
 [1.09122362e-01 3.71439435e-01 5.19438203e-01]]
acc = 0.00 
Score=1.4365953374491627e-90
================predict===============
[1 0 1 0 0 0]
[[2.84673583e-10 9.99210272e-01 7.89727447e-04]
 [4.91871453e-01 1.29224683e-01 3.78903864e-01]
 [1.19346389e-01 5.49123906e-01 3.31529705e-01]
 [5.61108375e-01 9.68408864e-02 3.42050738e-01]
 [5.96739514e-01 8.01480995e-02 3.23112387e-01]
 [5.76084469e-01 8.78623081e-02 3.36053223e-01]]
acc = 66.67 
Score=1.3044306604920557e-90
================predict===============
[1 2 1 0 0 0]
[[6.66355743e-17 9.99978861e-01 2.11386289e-05]
 [4.35554761e-01 2.05687864e-01 3.58757374e-01]
 [1.99993599e-01 4.61749256e-01 3.38257145e-01]
 [5.494

Score=7.857955687372444e-91
================predict===============
[1 0 1 0 0 0]
[[0.00885769 0.67646961 0.3146727 ]
 [0.42741121 0.26840167 0.30418712]
 [0.24128995 0.39631078 0.36239926]
 [0.4332003  0.2649902  0.3018095 ]
 [0.43565648 0.26350632 0.30083719]
 [0.43436337 0.26423895 0.30139768]]
acc = 66.67 
Score=8.515344642614231e-91
================predict===============
[1 0 1 0 0 0]
[[0.00105312 0.81155308 0.1873938 ]
 [0.44469719 0.24666218 0.30864063]
 [0.21208287 0.4252038  0.36271334]
 [0.45810086 0.23872808 0.30317106]
 [0.46438111 0.23486083 0.30075806]
 [0.46104195 0.23672014 0.3022379 ]]
acc = 66.67 
Score=7.272485795106475e-91
================predict===============
[0 1 0 1 1 1]
[[0.5666668  0.08521958 0.34811362]
 [0.27453327 0.41368382 0.31178291]
 [0.3592043  0.29797761 0.34281809]
 [0.27376549 0.41484393 0.31139058]
 [0.27350299 0.41523581 0.3112612 ]
 [0.27363642 0.41502904 0.31133455]]
acc = 16.67 
Score=1.2949735992104857e-90
================predict===============

# 讀取模型

In [18]:
import pickle
# 调用模型
z = np.array([[1,0,1,0,0,0]]).T
input = open('model.pkl', 'rb')
model = pickle.load(input)
input.close()
model.predict(z)

print("觀察序列:" + str(z.T))
print("預測:" + str(model.predict(z)))
count = 0
for i in range(len(z)):
    if z[i][0] == model.predict(z)[i]:
        count += 1
print("Acc:" + str(count/len(z)))

觀察序列:[[1 0 1 0 0 0]]
預測:[1 0 2 0 0 0]
Acc:0.8333333333333334
